### ISSUE TITLE
Tutorial for installing the script with the database?

### ISSUE THREAD

**Issue by Flogerbe** [cmlinac/joglogs#114]
Is it possible to add a tutorial for installing the script with the database? I am concoinced at this level because I can not deploy completely the application?

**Comment by cmlinac** [comment]
That's a good idea, I'll leave this open until the tutorial is added to the readme.

In the meantime, in the top-level `.env` file, if you set the environment to `TEST` or set the property  `FORCE=FORCE`, it will force-create the schema in the local DB you have set up under `LOCAL_DB` in the .env file, all it requires is that the database is previously created (with a simple CREATE DATABASE LOCAL_DB query).

**Comment by Flogerbe** [comment]
Hello, is it possible to explain to me how to use this webapp please? I really block
