### ISSUE TITLE
Convert old UI into React Components

### ISSUE THREAD

**Issue by cmlinac** [cmlinac/joglogs#12]
Make a similar site but in react, this is a very large issue

**Comment by SagerWilliams** [comment]
Unique components to create in react:
All pages:
- Navbar (num x3)
- Hero image/video (num x3)
- Footer (num x3)
- Modal for Sign in, Sign up, Load, Error
Home Page:
- Side Image (num x3)
- Side Text (num x3)
Setup Page:
- Form card (fancy card with title that holds a form)
- Form pieces (Start/Goal form)
Calendar Page:
- Calendar
- Sync button

**Comment by cmlinac** [comment]
Proposal: when you start on a component, put a . to the right of it. When you are finished, change that . to an x
