### ISSUE TITLE
Harden UI

### ISSUE THREAD

**Issue by cmlinac** [cmlinac/joglogs#14]
Display error messages, enforce login, don't show login buttons when they are logged in, etc

**Comment by cmlinac** [comment]
Tell user if their password is insufficient and WHY it's insufficient on sign up

**Comment by aaronphillips929** [comment]
Add back in mobile button for navbar

**Comment by SagerWilliams** [comment]
Add functionality to "Agree to Terms and Conditions" checkbox on sign up modal.

**Comment by SagerWilliams** [comment]
What if user submits incomplete, or incompatible info?

**Comment by cmlinac** [comment]
Picked this up, starting with getting user login checking in our app and going from there.

**Comment by cmlinac** [comment]
FORM VALIDATION
- User tries to log in/sign up with invalid email (doesn't meet requirements)
- User tries to log in/sign up with invalid password (doesn't meet requirements)
- User doesn't click the T&C box when they sign up
- User doesn't pick enough run days
- User tries to pick a long run on a day they didn't say they would run

ERROR HANDLING
- User tries to sign up with an email that exists
- User tries to log in and username/password is wrong
- User tries to access Setup or Calendar when not logged in

**Comment by cmlinac** [comment]
There's some kind of issue with conditional rendering of login/logout where the state isn't updating after you log in. Refreshing the page makes the proper thing happen. Most likely need to update state in the component as well as in the parent componenent

**Comment by cmlinac** [comment]
Switch Setup & Calendar to conditionally render before redirecting
